In [2]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib as plt

In [6]:
df = pd.read_csv('S06-hw-dataset-04.csv')

In [10]:
display(df.head())
df.info()
display(df.describe())

,id,f01,f02,f03,f04,f05,f06,f07,f08,f09,...,f52,f53,f54,f55,f56,f57,f58,f59,f60,target
0,1,-1.250210,1.423474,-0.225004,-4.023138,-0.832729,-0.550874,1.772090,2.761690,-0.698750,...,10.938269,0.501178,1.600001,0.314212,1.209735,1.355697,-5.338924,1.153944,-0.153934,0
1,2,0.074328,0.376429,0.212831,-0.502074,2.017405,0.625496,1.943785,1.242030,-0.524090,...,7.775262,-4.550195,6.272586,-0.932162,-0.228543,1.735220,-3.827828,0.292165,0.273720,0
2,3,0.638481,0.060968,0.746760,2.479653,-0.292858,-0.078139,-2.918423,-0.013186,1.009135,...,-4.448447,-9.593179,-3.093519,0.029321,0.605511,0.829103,-0.085985,2.891408,0.766221,0
3,4,1.712916,-1.350969,-0.256473,1.622074,-0.445141,0.911932,-3.440345,1.505192,-1.104348,...,-1.619072,-3.237479,-5.474038,-1.582475,0.198137,3.823409,0.880395,1.148610,0.136732,0
4,5,0.905676,-0.206545,-0.068806,4.086026,-1.010045,-0.772644,-4.207688,2.506104,1.589143,...,-2.396844,-10.540129,-5.532811,-1.231203,0.000119,4.298572,-1.558235,0.924673,0.111668,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 62 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      25000 non-null  int64
 1   f01     25000 non-null  float64
 2   f02     25000 non-null  float64
 3   f03     25000 non-null  float64
 4   f04     25000 non-null  float64
 5   f05     25000 non-null  float64
 6   f06     25000 non-null  float64
 7   f07     25000 non-null  float64
 8   f08     25000 non-null  float64
 9   f09     25000 non-null  float64
 10  f10     25000 non-null  float64
 11  f11     25000 non-null  float64
 12  f12     25000 non-null  float64
 13  f13     25000 non-null  float64
 14  f14     25000 non-null  float64
 15  f15     25000 non-null  float64
 16  f16     25000 non-null  float64
 17  f17     25000 non-null  float64
 18  f18     25000 non-null  float64
 19  f19     25000 non-null  float64
 20  f20     25000 non-null  float64
 21  f21     25000 non-null  float64
 22  f22     25000 non-null  float64
 23  f23     25000 non-null  float64
 24  f24     25000 non-null  float64
 25  f25     25000 non-null  float64
 26  f26     25000 non-null  float64
 27  f27     25000 non-null  float64
 28  f28     25000 non-null  float64
 29  f29     25000 non-null  float64
 30  f30     25000 non-null  float64
 31  f31     25000 non-null  float64
 32  f32     25000 non-null  float64
 33  f33     25000 non-null  float64
 34  f34     25000 non-null  float64
 35  f35     25000 non-null  float64
 36  f36     25000 non-null  float64
 37  f37     25000 non-null  float64
 38  f38     25000 non-null  float64
 39  f39     25000 non-null  float64
 40  f40     25000 non-null  float64
 41  f41     25000 non-null  float64
 42  f42     25000 non-null  float64
 43  f43     25000 non-null  float64
 44  f44     25000 non-null  float64
 45  f45     25000 non-null  float64
 46  f46     25000 non-null  float64
 47  f47     25000 non-null  float64
 48  f48     25000 non-null  float64
 49  f49     25000 non-null  float64
 50  f50     25000 non-null  float64
 51  f51     25000 non-null  float64
 52  f52     25000 non-null  float64
 53  f53     25000 non-null  float64
 54  f54     25000 non-null  float64
 55  f55     25000 non-null  float64
 56  f56     25000 non-null  float64
 57  f57     25000 non-null  float64
 58  f58     25000 non-null  float64
 59  f59     25000 non-null  float64
 60  f60     25000 non-null  float64
 61  target  25000 non-null  int64
dtypes: float64(60), int64(2)
memory usage: 11.8 MB

,id,f01,f02,f03,f04,f05,f06,f07,f08,f09,...,f52,f53,f54,f55,f56,f57,f58,f59,f60,target
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,...,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.00000
mean,12500.500000,-0.000386,-0.004872,0.003202,0.335329,-0.000563,-0.010118,0.001182,0.957385,-0.004658,...,-0.166251,-3.387506,1.749793,-0.013017,-0.001383,0.893365,-0.909479,0.000570,-0.000754,0.04920
std,7217.022701,1.001623,0.995606,1.004367,3.207537,0.993965,1.002172,2.432162,1.830223,1.013470,...,4.234741,4.331576,5.318660,1.001594,0.996409,2.445185,1.962618,0.994320,0.997167,0.21629
min,1.000000,-4.370993,-4.087073,-4.103875,-13.249937,-4.118778,-3.895974,-8.883224,-8.132548,-4.068933,...,-20.021141,-18.332290,-20.336666,-4.349216,-4.119472,-9.508509,-7.919287,-4.038312,-3.812255,0.00000
25%,6250.750000,-0.680165,-0.675100,-0.675426,-1.750048,-0.669764,-0.674374,-1.647977,-0.217260,-0.688278,...,-2.897904,-6.278403,-1.775889,-0.689962,-0.676191,-0.735473,-2.226959,-0.666367,-0.665861,0.00000
50%,12500.500000,0.001859,-0.000247,0.013272,0.403483,-0.001309,-0.005994,-0.011349,0.963009,0.000414,...,-0.396946,-3.462072,1.931851,-0.020933,-0.004193,0.888535,-0.923354,0.004381,0.002420,0.00000
75%,18750.250000,0.679702,0.659523,0.683437,2.486453,0.672299,0.652629,1.658680,2.167758,0.681040,...,2.344956,-0.578540,5.473886,0.661300,0.673722,2.516790,0.395648,0.666474,0.665918,0.00000
max,25000.000000,4.208888,3.984564,3.793442,15.288250,4.020733,4.279607,9.538525,9.321099,4.261349,...,20.717964,18.818764,20.688069,4.338337,3.902131,11.880651,6.778980,3.834922,4.012639,1.00000

In [19]:
target_counts = df['target'].value_counts()
target_shares = df['target'].value_counts(normalize=True)
print(target_counts)
print(target_shares)
missing = df.isnull().sum()
print(missing[missing > 0] if missing.sum() > 0 else 0)

target
0    23770
1     1230
Name: count, dtype: int64
target
0    0.9508
1    0.0492
Name: proportion, dtype: float64
0

In [21]:
X = df.drop(columns=['id', 'target'])
y = df['target']
print(f"Размерность X: {X.shape}")
print(f"Размерность y: {y.shape}")

Размерность X: (25000, 60)
Размерность y: (25000,)